let message = document.getElementById("text");
let container = document.getElementById("container");
let messages = [
  "You are loved, even when you don't feel it. 💙",
  "Your feelings are valid, and you deserve support. 🌿",
  "The world is better with you in it. 🌎💖",
  "It's okay to rest. Healing takes time. 🛌",
  "You are not alone. Reach out, even if it's hard. 🤝",
  "You are stronger than your darkest thoughts. 💪",
  "This moment will pass. Hold on. 🌅",
  "Your story isn’t over yet. Keep writing it. 📖",
  "Breathe. One step at a time. 🌬️",
  "Even small progress is progress. Keep going. 🚶",
  "You deserve kindness, especially from yourself. 💕",
  "Someone cares about you more than you know. 🤗",
  "It’s okay to ask for help. You don’t have to do this alone. 🆘",
  "You have survived every hard day before. You’ll survive this too. 🌱",
  "Your feelings don’t define your worth. You are enough. 🌟",
  "It’s okay to feel lost sometimes. You’ll find your way. 🧭",
  "You don’t need to have everything figured out right now. ⏳",
  "You are growing, even in pain. 🌿",
  "There’s a future version of you who is so glad you kept going. 🔆",
  "The people who love you want you here. 💖",
  "A bad day doesn’t mean a bad life. 🌧️➡️🌞",
  "Your mind is lying to you—there is hope. 🌈",
  "Pain is temporary, but your strength is forever. 💪",
  "You are not broken, just in need of healing. 🩹",
  "You are more than your struggles. 🦋",
  "There is beauty in you that you cannot see right now. 🎨",
  "You are allowed to take up space in this world. 🌍",
  "Even if today was hard, tomorrow is a new chance. 🌅",
  "You don’t have to be perfect to be loved. ❤️",
  "Take things one breath at a time. 🌬️",
  "Your heart is still beating—keep fighting. 💓",
  "What you’re feeling right now is temporary. You won’t feel like this forever. ⏳",
  "There’s a sunrise waiting for you. 🌄",
  "You deserve love, peace, and happiness. 💕",
  "Someone out there needs you, even if you don’t see it yet. 🤝",
  "You are a light, even if you don’t feel like it. 🔦",
  "Your existence is not a mistake. 🌟",
  "It’s okay to cry. Tears are proof you’re human. 😢",
  "You are worthy of help and support. 🏥",
  "Taking care of yourself is not selfish. 🛀",
  "Every heartbeat means you have another chance. 💗",
  "Your future self will thank you for holding on. ⏳",
  "Even the stars needed darkness to shine. ✨",
  "You are irreplaceable. No one else can be you. 🌍",
  "You are doing better than you think. 💙",
  "There’s so much left for you to experience. 🎢",
  "Let go of guilt. You deserve peace. ☁️",
  "Your happiness is possible, even if you can’t see it now. 🌈",
  "I believe in you. You can get through this. 💫",
];

container.addEventListener("mouseover", () => {
  let randomIndex = Math.floor(Math.random() * messages.length);
  message.innerHTML = messages[randomIndex];
});
